COUNTRY_NAMES = ["Afghanistan", "Albania", "Algerie", "Andorra", "Angola", "Antigua og Barbuda", "Argentina", "Armenia", "Aserbajdsjan", "Austerrike", "Aust-Timor", "Australia"
                 ,"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgia", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia-Hercegovina", "Botswana", "Brasil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi"
                 ,"Canada", "Chile", "Colombia", "Costa Rica", "Cuba"
                 ,"Danmark", "De forente arabiske emirater", "Dei sameinte arabiske emirata", "Den dominikanske republikk", "Den dominikanske republikken", "Den sentralafrikanske republikk", "Den sentralafrikanske republikken", "Djibouti", "Dominica"
                 ,"Ecuador", "Egypt", "Ekvatorial-Guinea", "Elfenbenskysten", "Elfenbeinskysten", "El Salvador", "Eritrea", "Estland", "Eswatini", "Etiopia"
                 ,"Fiji", "Filippinene", "Filippinane", "Finland", "Frankrike"
                 ,"Gabon", "Gambia", "Georgia", "Ghana", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana"
                 ,"Haiti", "Hellas", "Honduras", "Hviterussland"
                 ,"India", "Indonesia", "Irak", "Iran", "Irland", "Island", "Israel", "Italia"
                 ,"Jamaica", "Japan", "Jemen", "Jordan"
                 ,"Kambodsja", "Kamerun", "Kapp Verde", "Kasakhstan", "Kenya", "Kina", "Kirgisistan", "Kiribati", "Komorene", "Komorane", "Kongo", "Kongo-Brazzaville", "Kosovo", "Kroatia", "Kuwait", "Kviterussland", "Kypros"
                 ,"Laos", "Latvia", "Lesotho", "Libanon", "Liberia", "Libya", "Liechtenstein", "Litauen", "Luxemburg", "Luxembourg"
                 ,"Madagaskar", "Malawi", "Malaysia", "Maldivene", "Maldivane", "Mali", "Malta", "Marokko", "Marshalløyene", "Marshalløyane", "Mauritania", "Mauritius", "Mexico", "Mikronesiaføderasjonen", "Moldova", "Monaco", "Mongolia", "Montenegro", "Mosambik", "Myanmar"
                 ,"Namibia", "Nauru", "Nederland", "Nepal", "New Zealand", "Ny-Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Nord-Korea", "Nord-Makedonia", "Norge", "Noreg"
                 ,"Oman"
                 ,"Pakistan", "Palau", "Palestina", "Panama", "Papua Ny-Guinea", "Paraguay", "Peru", "Polen", "Portugal"
                 ,"Qatar"
                 ,"Romania", "Russland", "Rwanda"
                 ,"Saint Kitts og Nevis", "St. Kitts og Nevis", "Saint Lucia", "St. Lucia", "Saint Vincent og Grenadinene", "St. Vincent og Grenadinene", "Saint Vincent og Grenadinane", "St. Vincent og Grenadinane", "Salomonøyene", "Salomonøyane", "Samoa", "San Marino", "São Tomé og Príncipe", "Saudi-Arabia", "Senegal", "Serbia", "Seychellene", "Seychellane", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Somalia", "Spania", "Sri Lanka", "Storbritannia", "Sudan", "Surinam", "Sveits", "Sverige", "Syria", "Sør-Afrika", "Sør-Korea", "Sør-Sudan"
                 ,"Tadsjikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad og Tobago", "Tsjad", "Tsjekkia", "Tunisia", "Turkmenistan", "Tuvalu", "Tyrkia", "Tyskland"
                 ,"Uganda", "Ukraina", "Ungarn", "Uruguay", "USA", "Usbekistan"
                 ,"Vanuatu", "Vatikanstaten", "Venezuela", "Vietnam"
                 ,"Zambia", "Zimbabwe"
                 ,"Østerrike", "Øst-Timor"]